version: "3.8"
services:
  ui:
    build:
      context: ./ui
      args:
        VITE_API_URL: http://localhost:8000
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - vending-machine

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - VENDING_MACHINE_PORT=8000
    ports:
      - "8000:8000"
    networks:
      - vending-machine

networks:
  vending-machine:
