FROM node:20-alpine3.18 as build

RUN npm install -g pnpm

ARG VITE_API_URL 
ENV VITE_API_URL=${VITE_API_URL}

WORKDIR /usr/src/app

COPY package*.json pnpm-lock.yaml* ./

RUN pnpm i

COPY . .

EXPOSE 5173

CMD pnpm run dev
